<?php

namespace AppBundle\Repository;

/**
 * BeerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FermentingCartographyRepository extends \Doctrine\ORM\EntityRepository
{
}
